name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: check commit messages for skips
        if: ${{ contains(join(github.event.commits.*.message), '#skip') }}
        run: echo "Found commits to skip"

  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run tests
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && ! contains(join(github.event.commits.*.message), '#skip') }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
      - name: Discord Message Notify
        uses: appleboy/discord-action@v1.0.0
        if: ${{ success() }}
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          username: 'GitHub Bot'
          color: '#14A44D'
          message: A new version of Pokedex deployed!
      - name: Discord Message Notify
        uses: appleboy/discord-action@v1.0.0
        if: ${{ ! success() }}
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          username: 'GitHub Bot'
          color: '#DC4C64'
          message: Build failed!

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        if: ${{ github.event_name == 'push' && ! contains(join(github.event.commits.*.message), '#skip') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
